# Generated by Django 5.0.7 on 2024-12-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
