# Generated by Django 5.1.4 on 2024-12-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerapp", "0017_review_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="images/")),
                ("body", models.TextField(max_length=2000, null=True)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "main_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamerapp.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamerapp.sub_category",
                    ),
                ),
                (
                    "sub_subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamerapp.sub_subcategory",
                    ),
                ),
            ],
        ),
    ]
