# Generated by Django 5.0.7 on 2024-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0017_review_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, null=True)),
                ('topic', models.CharField(max_length=64)),
                ('body', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
