# Generated by Django 5.1.4 on 2024-12-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerapp", "0019_alter_blog_post_main_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_post",
            name="main_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gamerapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gamerapp.sub_category",
            ),
        ),
        migrations.AlterField(
            model_name="blog_post",
            name="sub_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gamerapp.sub_subcategory",
            ),
        ),
    ]
