# Generated by Django 5.0.7 on 2024-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0019_alter_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_post',
            old_name='author',
            new_name='blog_author',
        ),
    ]
