# Generated by Django 5.1.4 on 2024-12-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerapp", "0020_alter_blog_post_main_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog_post",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="blog_post",
            name="sub_category",
        ),
        migrations.RemoveField(
            model_name="blog_post",
            name="sub_subcategory",
        ),
    ]
