# Generated by Django 5.1.4 on 2024-12-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerapp", "0021_remove_blog_post_main_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_post",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
